73: fn:graphemes
qt4cg/qtspecs pull request #1068
Opened 2024-03-08 01:51 UTC by Arithmeticus

First draft of `fn:graphemes`, in response to discussion at #73 .

A battery of tests will be submitted as a PR to the qt4tests repository.

2024-03-08 02:03 UTC, Arithmeticus commented
First draft of tests: https://github.com/qt4cg/qt4tests/pull/77

2024-03-08 09:41 UTC, ChristianGruen requested changes

2024-03-08 09:41 UTC, ChristianGruen commented on specifications/xpath-functions-40/src/function-catalog.xml
> +         <p>If <code>$value</code> is a zero-length string or the empty sequence, the function returns
A minor issue: This condition could be limited to the empty sequence, as (I assume) the core split algorithm implies that a zero string will return zero characters.

2024-03-08 09:41 UTC, ChristianGruen commented on specifications/xpath-functions-40/src/function-catalog.xml
> +            <fos:option key="grapheme-clusters">
Maybe just `clusters`.

I failed finding information on the two variants in the quoted reference. Could you possibly add some more details how a legacy implementations would differ from the default implementation?

2024-03-08 09:41 UTC, ChristianGruen commented on specifications/xpath-functions-40/src/function-catalog.xml
> +      <fos:examples>
Examples for both the Legacy and Extended variant would be helpful to understand the difference.

2024-03-08 11:35 UTC, michaelhkay commented
It might be helpful in the examples to indicate what the actual codepoints in the input strings are, rather than relying on the way the browser renders them. For example, some of the characters might be in composed or decomposed form, and we can't tell just by looking at them. One solution might be to write the example as `let $s := "..." return [string-to-codepoints($s), graphemes($s)]`.

2024-03-12 02:30 UTC, Arithmeticus commented on specifications/xpath-functions-40/src/function-catalog.xml
> +            <fos:option key="grapheme-clusters">
see question raised below

2024-03-12 02:30 UTC, Arithmeticus commented on specifications/xpath-functions-40/src/function-catalog.xml
> +      <fos:examples>
see question raised below

2024-03-12 02:35 UTC, Arithmeticus commented
Regarding legacy versus extended grapheme clusters: I would like to suggest that we can drop the legacy as a required option.

> The Unicode Standard provides a default algorithm for determining grapheme cluster boundaries; the default grapheme clusters are also known as **extended grapheme clusters**. For backwards compatibility with earlier versions of this specification, the Standard also defines a profile for **legacy grapheme clusters**.

Of course, nothing forbids an implementer from supporting legacy, per the options map rules.

That will simplify the specs and tests, and not saddle implementations with legacy support.  Any objections?

2024-03-12 02:52 UTC, Arithmeticus commented on specifications/xpath-functions-40/src/function-catalog.xml
> +         <p>If <code>$value</code> is a zero-length string or the empty sequence, the function returns
Here I tried merely to follow `fn:characters`. If `fn:graphemes('')` should entail `''` then `fn:characters` should do so as well, no?

2024-03-12 06:54 UTC, ChristianGruen commented
I suggest dropping the options argument. The specification should ideally not motivate implementors to do things differently unless there are compelling reasons to do so.

2024-03-12 06:56 UTC, ChristianGruen commented on specifications/xpath-functions-40/src/function-catalog.xml
> +         <p>If <code>$value</code> is a zero-length string or the empty sequence, the function returns
I agree. Consistency wins.

2024-03-26 07:43 UTC, ChristianGruen approved these changes

2024-05-14 16:14 UTC, ndw commented
The CG agreed to merge this PR at [meeting 077](https://qt4cg.org/meeting/minutes/2024/05-14.html)

2024-05-14 16:15 UTC, merged

2024-05-14 21:36 UTC, gimsieke reviewed
Since this has already been merged, I should probably issue a new PR?

2024-05-14 21:36 UTC, gimsieke commented on specifications/xpath-functions-40/src/function-catalog.xml
> +               <fos:result>char(0x1F476) || char(0x308) || char(0x1F6D1)</fos:result>
Shouldn’t this `char(0x308)` read `char(0x200D)`?

2024-05-14 22:44 UTC, ChristianGruen commented
> Since this has already been merged, I should probably issue a new PR?

Yes, that’ll probably be the easiest way.