Fix colon issue in URI parsing
qt4cg/qtspecs pull request #1097
Opened 2024-03-18 16:22 UTC by ndw

In the course of reviewing the tests for `fn:parse-uri`, I discovered (or perhaps more correctly, @ChristianGruen discovered) that the rules for matching Windows drive letters are inconsistent. This PR fixes that inconsistency.

2024-03-19 12:30 UTC, ChristianGruen requested changes

2024-03-19 12:30 UTC, ChristianGruen commented on specifications/xpath-functions-40/src/function-catalog.xml
> +         the first match group. If the second character in the <emph>string</emph> is <code>|</code>,
```suggestion
         the first match group. If the third character in the <emph>string</emph> is <code>|</code>,
```

2024-03-19 14:32 UTC, ndw commented
Fix pushed. Thank you.

2024-03-19 14:39 UTC, ChristianGruen approved these changes

2024-03-19 17:46 UTC, ndw commented
It's a fair question. I know I've seen `file:///C|/path` in the wild, but maybe not often enough to special case it.

2024-03-26 17:12 UTC, ndw commented
The CG agreed to merge this PR without further discussion at [meeting 071](https://qt4cg.org//meeting/minutes/2024/03-26.html)

2024-03-26 17:17 UTC, merged