Attempt to resolve #1387 by clarifying the encoding rules
qt4cg/qtspecs pull request #1388
Opened 2024-08-14 10:26 UTC by ndw

I decided to put this in a separte PR so that it can be reviewed in isolation. I don't expect it to be controversial, exactly, but it may require adjustment.

2024-08-14 10:49 UTC, ChristianGruen reviewed
I wonder what could be done to simplify the rules a little:

1. I would really appreciate if we had fixed set of characters that are encoded. Would you mind dropping the `path-separator` and `query-separator` options, or do you think they are essential?
2. If we need to keep them, I assume the `path-separator` would need to be considered as well when encoding path segments. In addition, we’ll have to write more tests.
3. Maybe the lists of characters to be encoded could be represented as simple strings (regex or literals).

2024-08-14 11:09 UTC, ChristianGruen commented
> I'm really sympathetic to trying to simplify the set of characters but it's tricky because the URI spec/user expectations intersection is different in the different cases. I'll see if I can think of a simpler presentation.

That would be great. I’ve been thinking about the time we’ve already spent on those two functions, and with every new rule I wonder if we’ll manage to build something that’s going to be solid (unfortunately, we don’t have a third implementer around who might encounter things that we both haven’t noticed yet). Removing the convenience options might improve the situation: If someone really needs more advanced features to build URIs, it’s fairly easy to write some custom code.

Either way, URIs are tough…

2024-09-02 11:28 UTC, ChristianGruen requested changes
I took the liberty of marking this with “request changes”. I think (as proposed) we should either simplify the rules again or consider `path-separator`, too.

2024-09-03 01:17 UTC, Arithmeticus commented on specifications/xpath-functions-40/src/function-catalog.xml
> +        The encoding performed replaces any control characters (code points less than 0x20)
code points > codepoints

2024-09-03 01:18 UTC, Arithmeticus commented on specifications/xpath-functions-40/src/function-catalog.xml
> +        The encoding performed for the fragment replaces any control characters (code points less than 0x20)
code points > codepoints

2024-09-10 16:08 UTC, ndw commented
The CG agreed to close this PR without further action at [meeting 089](https://qt4cg.org/meeting/minutes/2024/09-10.html)

2024-09-10 16:08 UTC, closed without merging