Align type tests
qt4cg/qtspecs pull request #1429
Opened 2024-09-08 15:43 UTC by line-o

fixes #1403

Allow Array and Map tests to omit the asterisk to match any array or map.

- `array()` <> `array(*)`
- `map()` <> `map(*)`

2024-09-08 17:42 UTC, michaelhkay requested changes
`<g:string>*?</g:string>` is wrong. It needs to be `<g:optional><g:string>*</g:string></g:optional>`

2024-09-08 17:54 UTC, michaelhkay commented
I think it would also be a good idea to make clear in 3.3.2.8 and 3.3.2.9 that the two forms are equivalent.

2024-09-08 20:13 UTC, line-o commented
@michaelhkay I try to make that clear in 3.3.2.8 (see screenshot) and similarly in 3.3.2.9

<img width="809" alt="Screenshot 2024-09-08 at 16 07 53" src="https://github.com/user-attachments/assets/3af4a1c0-e017-49be-9620-76a2f621a3ed">

Do you have a suggestion how to make that point clearer?
Adding `map() and map(*) are equivalent.` to `The AnyMapTest map() or map(*) matches any map.` seems redundant.

2024-09-08 20:28 UTC, michaelhkay commented
Perhaps in 3.3.2.9 clause 1(b) change `B is array(*)` to `B is an AnyArrayTest (that is, array() or array(*))` (and similarly for maps). I'l leave it to you. But when there are two equivalent ways of saying the same thing, I think we need an occasional reminder that what we say about one form applies equally to the other.

2024-09-17 15:06 UTC, line-o commented
I did some work on section 3.3 Subtype Relationships that should drive the point home.

2024-09-17 16:29 UTC, ChristianGruen commented on specifications/xquery-40/src/expressions.xml
>                          <code>[ 1, 2 ] instance array(*)</code> returns <code>true()</code>
The one that was already in the spec:

```suggestion
                        <code>[ 1, 2 ] instance of array(*)</code> returns <code>true()</code>
```

2024-09-17 16:29 UTC, ChristianGruen commented on specifications/xquery-40/src/expressions.xml
> +                        <code>[ 1, 2 ] instance array()</code> returns <code>true()</code>
The copied one:

```suggestion
                        <code>[ 1, 2 ] instance of array()</code> returns <code>true()</code>
```

2024-10-01 14:46 UTC, line-o commented
It just occurred to me that if we would to accept this change we should also allow `record()` to be equal to `record(*)`.

2024-10-01 15:59 UTC, line-o commented
Since this change was rejected, should I close it myself?

2024-10-01 16:11 UTC, closed without merging

2024-10-01 16:11 UTC, ndw commented
At [meeting 092](https://qt4cg.org//meeting/minutes/2024/10-01.html), the CG declined to accept this PR.

2024-10-01 16:20 UTC, ndw commented
It would have been fine if you had, but I didn't notice your question before I closed it :-)