1387 Another tweak to build-uri
qt4cg/qtspecs pull request #1440
Opened 2024-09-12 16:03 UTC by ndw

In #1387 @ChristianGruen observes that the `+` seems to be a special case in the `tel:` scheme. In fact, I think we concluded that the special case is that you shouldn't encode the path segment of a non-hierarchical URI.

This PR attempts to implement that.

2024-09-13 07:59 UTC, ChristianGruen requested changes
After having read the PR again, I think it needs to be improved a little:

`'a+b/c' => parse-uri()` returns a non-hierarchical path. With the current rules, the result of `'a+b/c' => parse-uri() => build-uri()` would be `a b`.

Maybe we should:

1. apply the rule to all path segments and
2. not consider the `hierarchical` attribute, but rather check if a supplied scheme is known to be non-hierarchical?

2024-09-13 09:47 UTC, ChristianGruen approved these changes

2024-09-16 08:15 UTC, ChristianGruen requested changes
Copied from my comment, and slightly revised:

`'a+b/c' => parse-uri()` returns a non-hierarchical path. With the proposed rules, if I understand it correctly, the result of `'a+b/c' => parse-uri() => build-uri()` would be `a b`.

Maybe we should:

1. apply the rule to all path segments and
2. not consider the `hierarchical` attribute, but rather check if a scheme is supplied and if it is known to be non-hierarchical?

2024-09-16 10:11 UTC, ndw commented
Yes, you've persuaded me. And I've tried to change the rules accordingly. It was not easy to work out how best to describe those rules. Comments welcome.

2024-09-16 12:37 UTC, ChristianGruen reviewed
@ndw Looks and feels good.

1. I noticed only now that the new rule of what’s *non-hierarchical* is pretty similar to what’s found further above for schemes. Maybe it would be reasonable to use exactly the same rule (if we believe that this makes sense)?

> A URI is considered to be non-hierarchical if either the hierarchical key is present in the $parts map with the value false() or if the scheme is known to be non-hierarchical. (In other words, schemes are hierarchical by default.)

2. I now get `jar:file:/C:/Program Files/test.jar!/foo/bar` instead of `jar:file:/C:/Program%20Files/test.jar!/foo/bar` for the test case `fn-build-uri-from-parse-028`. Do you think we can/should live with that?

2024-09-17 12:17 UTC, ChristianGruen approved these changes

2024-09-17 12:18 UTC, ChristianGruen commented
I’ve readded `Propose Merge without Discussion`, maybe we can add it to today’s list.

2024-09-17 16:04 UTC, ndw commented
The CG agreed to merge this issue without discussion at [meeting 090](https://qt4cg.org/meeting/minutes/2024/09-17.html).

2024-09-17 16:04 UTC, merged