Explicitly mention subtypes for arrays and maps
qt4cg/qtspecs pull request #153
Opened 2022-09-26 12:14 UTC by line-o

Reword section 3.6.4 for map and array type tests to explicitly mention sub typing and link to the relevant section.

2022-09-28 10:22 UTC, michaelhkay requested changes
Please avoid adding explicit references to "clause numbers" like 4.c - there's no easy way to preserve such references when new clauses are added. Unfortunately we don't have machinery for doing this (it would be nice to have a `<clauseref ref="..."/>`) and in its absence I would suggest introducing a defined term "This rule and the four rules that follow are referred to as the `<termdef id="dt-map-subtyping-rules"/>`", and then use a termref. Alternatively you might be able to solve the problem by making the top-level list items (for example "Conditions for functions, maps, and arrays") into section headings, making them a bit more granular, and using a specref.

2022-09-29 15:00 UTC, line-o commented
Thank you for your feedback @michaelhkay. I will do one of the two suggested edits. Do you have a preference where to add the subtype examples?

2022-09-29 15:28 UTC, michaelhkay commented
Examples should be as close as possible to the rule that they elucidate. So if you want an example of how union(A,B) is a subtype of union(A, B, C), then it belongs in 2.c.

It would be nice to have some uniformity; having examples for some of the rules and not others may be appropriate if some of the rules are more obvious than others, but it shouldn't be done purely on a whim.

2022-10-08 22:00 UTC, michaelhkay reviewed
I have done a significant re-vamp of the section on subtyping item types, with a lot more examples and explanations; and I have added cross-references from the definitions of map, array, function,and record types to the section where the subtyping rules are defined. I think that means this PR can be dropped; but please check the new draft.

2022-10-11 11:22 UTC, line-o commented
@michaelhkay https://qt4cg.org/specifications/xquery-40/xquery-40.html#id-array-test does not mention subtypes explicitly. 

> The [AnyArrayTest](https://qt4cg.org/specifications/xquery-40/xquery-40.html#doc-xquery40-AnyArrayTest) array(*) matches any array. The [TypedArrayTest](https://qt4cg.org/specifications/xquery-40/xquery-40.html#doc-xquery40-TypedArrayTest) array(X) matches any array in which every array member matches the [SequenceType](https://qt4cg.org/specifications/xquery-40/xquery-40.html#doc-xquery40-SequenceType) X.

Does now have the *hint* at sequence types but I still believe that this should be made more explicit.
Or were your changes just not deployed yet?

2022-10-11 11:55 UTC, michaelhkay commented
I (a) added cross-reference to where subtypes are defined and explained, and (b) added a lot more explanation and examples to the section on subtyping. You can see the changes in https://qt4cg.org/pr/202/xquery-40/xpath-40.html - at the end of 3.6.4.4 there is a forwards reference to 3.7.2.8.

2022-10-12 10:53 UTC, line-o commented
@michaelhkay Thanks for the link, the changes you made are very good and exhaustive.
I still see the need to either

- update the information in the XQuery spec itself
- cross reference to the XPath spec instead - removing the duplication

2022-10-12 13:58 UTC, michaelhkay commented
The text in the XPath and XQuery specs comes from common source, so it should be identical. However, it might be that cross-reference links aren't fully working yet.

2022-10-19 16:32 UTC, ndw commented
Formatted versions of the specifications with this PR applied [are available](https://qt4cg.org/#pr-153)

2022-11-15 20:48 UTC, michaelhkay commented
This PR has been subsumed by PR #202 so I think it can now be closed with no further action.

2022-11-15 20:48 UTC, closed without merging

2022-11-16 11:06 UTC, line-o commented
Thanks for taking this from here and clarify sub typing! @michaelhkay @ndw