NW for MK: Variadicity (166)
qt4cg/qtspecs pull request #197
Opened 2022-10-10 08:55 UTC by ndw

This PR is intended to be technically equivalent to #166.

I've reworked a series of MK commits so that they are independent; I fear we would wind up with merge conflicts otherwise and cleaning up the merge conflicts, without accidentally making some other change, seemed riskier than just teasing them apart and making them independent before we accept and merge them.

2022-10-13 02:45 UTC, Arithmeticus commented on specifications/xslt-40/src/xslt.xml
> +                        In refers to the definition of a function that can be called from within an XPath
In refers -> It refers

2022-10-13 03:22 UTC, Arithmeticus commented on specifications/xquery-40/src/expressions.xml
> +                        <term>Default function namespace.</term> This is an algorithm that takes as input
A namespace is not an algorithm. 
Suggested: "This is the namespace URI returned by the algorithm that...."
Is the algorithm anywhere described or defined? Xref.

2022-10-13 03:31 UTC, Arithmeticus commented on specifications/xquery-40/src/expressions.xml
> +                     <termdef id="dt-declared-functions"
Is there precedence in the specs for two paired definitions, one for the plural form of the noun and the other for the singular? On the face of it, the formula "Xs: the set of Xs" is circular, and should be rephrased in terms of the singular version, e.g., "Xs: the set of every X". But why is the plural version needed? 
Further: "a set" -- i.e., arbitrary? Or is it every declared function declared from the static context?

2022-10-17 23:07 UTC, Arithmeticus requested changes
The proposal is excellent. I have flagged points that touch primarily on clarity, structure, and overlap. This is also my first attempt at reviewing changes to the specs, and I have focused primarily on questions of consistency. You may find a number of misfires on my part. Just tell my why and I'll try not to repeat the error in future reviews.

2022-10-18 07:27 UTC, rhdunn requested changes

2022-10-18 07:27 UTC, rhdunn commented on specifications/grammar-40/xpath-grammar.xml
> +      <g:string>:=</g:string>
> In function calls, the = in := has been deleted (KeywordArgument). Will the discrepancy between : and := confuse users?

This is using the $variable syntax to declare a variable (parameter in this case), so using := here is consistent with other variable declarations and bindings.

Using : in the function calls, that is not using the $variable syntax to assign the parameter (which would conflict with passing a variable of that name to the function). Instead, it is using a syntax akin to map construction, which uses the key : value syntax.

If/when function argument binding extends to map keys (such as for an option map), then the parameter and map key assignment is uniform and consistent with map construction.

2022-10-18 07:27 UTC, rhdunn commented on specifications/grammar-40/xpath-grammar.xml
> -    <g:string>:=</g:string>
See my comment on the parameters. -- This is consistent with the way map construction works.

To me, `:=` is for variable assignment which would require a `$name` variable syntax. That would be ambiguous with passing a variable of that name to the function. It would also be less clear as to what is happening, making the code harder to read. Using `:=` with `$name` (if we used `$name` instead of just `name`) would break the Scripting Extension assignment expressions which allow you to do things like `$name := 123` to update the value of a variable.

2022-10-18 07:27 UTC, rhdunn commented on specifications/xquery-40/src/expressions.xml
> +                        <term>Default function namespace.</term> This is an algorithm that takes as input
We haven't discussed the capability of the default function namespace logic to support this additional complexity. As such, I would expect this to be the same text as the XQuery/XPath specs:
> [Definition: Default function namespace. This is a namespace URI or [absent](https://www.w3.org/TR/xpath-datamodel-31/#dt-absent)DM31. The namespace URI, if present, is used for any unprefixed QName appearing in a position where a function name is expected.] The URI value is whitespace normalized according to the rules for the xs:anyURI type in [Section 3.2.17 anyURI ](https://www.w3.org/TR/xmlschema-2/#anyURI)XS1-2 or [Section 3.3.17 anyURI ](https://www.w3.org/TR/xmlschema11-2/#anyURI)XS11-2.

2022-10-18 07:27 UTC, rhdunn commented on specifications/xquery-40/src/expressions.xml
> +                     processor using some <termref def="dt-implementation-defined"/> API.</termdef></p>
> or it may represent information registered with the processor using some API.

I find this part slightly confusing, as in order to define a function via an API you are not just registering information, you are defining the function. Maybe change this to:

> or it may be registered with the processor using some API.

2022-10-18 07:27 UTC, rhdunn commented on specifications/xquery-40/src/expressions.xml
> +                           <item><p>a parameter name (an <termref def="dt-expanded-qname"/>)</p></item>
> delete "parameter"

I think keeping parameter here makes sense as it is qualifying what the name is relating to.

2022-10-18 07:27 UTC, rhdunn commented on specifications/xslt-40/src/xslt.xml
> +                  the static context does not include variables bound in preceding-sibling <elcode>xsl:param</elcode> elements.</p>
> edit?: preceding-sibling > sibling

This is correct. -- It is saying that if a previous xsl:param has a default expression that defines some variables, then those variables are not in the static context/scope of the current xsl:param.

2022-10-18 10:40 UTC, michaelhkay commented on specifications/xslt-40/src/xslt.xml
> +                        In refers to the definition of a function that can be called from within an XPath
Yes to "It refers". But it (the term) doesn't refer to a "function" in the sense of "XDM function" or "function item". In 3.1 it was possible to gloss over the distinction, but this is no longer the case; the things in the static context ("declared function" objects) represent families of functions rather than single functions. (But there's a lot of legacy mess in this area and I haven't cleaned it up 100%. The 3.1 spec called this "function signatures" though it clearly contained more than the signature. And then it didn't really use it anyway, the binding rules for static function calls actually went to the dynamic context....

2022-10-18 10:44 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                     <termdef id="dt-declared-functions"
Agreed, this probably isn't ideal. Altogether, the terminology for the parts of the static and dynamic context is far from ideal, and it's difficult to sort out. Many of these "parts" are described using plural forms of the things they contain and I followed that convention, but it's not a good convention.

2022-10-18 11:08 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                     <item><p>A (possibly empty) set of <term>function annotations</term></p>
XDM says that functions have a set of annotations, but in XPath it's always an empty set.

2022-10-18 11:32 UTC, michaelhkay commented on specifications/xslt-40/src/xslt.xml
> +                        In refers to the definition of a function that can be called from within an XPath
Thanks for this very detailed review. As I work through it, I get to the point where it's hard to respond to every detailed point because changes that need to be made to one comment tend to invalidate subsequent comments. So I think the best approach is probably to attempt a second draft that takes into account as many of the comments as possible, focussing on those that are independent.

2022-10-18 14:37 UTC, cmsmcq commented
Three minor queries about declared functions:

* In 2.1.1, the replacement of the definition of *statically known function signatures* with definitions of *declared function* and *declared functions* has as a consequence that while the status quo explicitly says that those function signatures are available for reference from a named function reference, the new text does not.  Is that covered elsewhere?  If not, is it likely to matter?

* Working through the proposal I find myself increasingly uncomfortable that the denotation of *declared function* is not a function.  I wonder if the term *function declaration* would work better?  Or *function family*?

* I note that the description of the default function namespace allows implementation-defined algorithms for searching multiple namespaces and resolving conflicts; this makes me wonder whether we have a compelling reason to forbid such algorithms for resolving overlapping arity ranges.  (I don't think I have a preference, beyond adhering to the goose/gander principle.)

2022-10-18 14:54 UTC, michaelhkay commented
@cmsmcq 

> In 2.1.1, the replacement of the definition of statically known function signatures with definitions of declared function and declared functions has as a consequence that while the status quo explicitly says that those function signatures are available for reference from a named function reference, the new text does not. Is that covered elsewhere? If not, is it likely to matter?

I think we used to say it twice, we now only say it once. It's there in 4.4.2.3.

> Working through the proposal I find myself increasingly uncomfortable that the denotation of declared function is not a function. I wonder if the term function declaration would work better? Or function family?

Yes, me too. I was trying to minimise change to the 3.1 spec, but I'm increasingly persuaded that the 3.1 presentation which tries to maintain that there are two kinds of function, static functions and dynamic functions, is wrong. I'm now proposing to call the things in the static context "function definitions". I don't want to call them "function declarations" because that's a specific piece of syntax in XQuery, but I think that the name "function definitions" gets us away from the idea that a declared function is a kind of function.

> I note that the description of the default function namespace allows implementation-defined algorithms for searching multiple namespaces and resolving conflicts; this makes me wonder whether we have a compelling reason to forbid such algorithms for resolving overlapping arity ranges. (I don't think I have a preference, beyond adhering to the goose/gander principle.)

Unfortunately, the base text I was starting from included a speculative enhancement for resolving unprefixed function names, which is unrelated to this proposal. I'm trying to roll that back, but the changes muddy the diff.

2022-10-18 21:13 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +               To obtain a 3-argument function that binds to arguments 1, 2, and 5 of <code>fn:format-date</code>,
No, what is obtained is an arity-3 function item with the default values for the other two arguments present in its closure.

2022-10-18 21:14 UTC, michaelhkay commented on specifications/grammar-40/xpath-grammar.xml
> +      <g:string>:=</g:string>
We decided to use ":=".

2022-10-19 16:34 UTC, ndw commented
Formatted versions of the specifications with this PR applied [are available](https://qt4cg.org/#pr-197)

2022-10-25 01:55 UTC, cmsmcq commented
Some incomplete and unsystematic notes:

* Is it intended that in section 2.2.1 Static Context of XPath, in the description of **function definition**, both *required type* and *default value* are glossed as "(a sequence type)"?  It seems unexpected enough that I suspect a copy/paste error.
* I think the sentence "It is not acceptable to have a function definition with one required parameter and another (with the same name) having three optional parameters", would do its work better without the parenthesis marks.
* A propos the sentence "Implementations must ensure that no two declared functions have the same [expanded QName](https://qt4cg.org/pr/197/xquery-40/xpath-40-autodiff.html#dt-expanded-qname) and overlapping arity ranges (even if the signatures are consistent)."
  * The term "declared function" seems important and is used in several places, but is nowhere defined in the XPath spec.  Does it mean a function definition in the statically known function definitions? ... in the dynamically known function definitions?
  * The requirement that no two declared functions have certain properties entails that we need a clean story about how to tell whether a declared function *f1* is the same declared function as a declared function *f2*, or they are different functions.  (I suspect this need is particularly acute when there is some possibility that the same module definition [for some definition of "same"] might by accident or design be referenced twice under different URIs, but the need is probably more general.  I don't think we want complicated rules, just a clear one.)  
* In section 2.3.4 Consistency constraints, the last bullet item appears to be redundant.  It says "Every [function definition](https://qt4cg.org/pr/197/xquery-40/xpath-40-autodiff.html#dt-function-definition) in the [statically-known function definitions](https://qt4cg.org/pr/197/xquery-40/xpath-40-autodiff.html#dt-statically-known-function-definitions) of the [static context](https://qt4cg.org/pr/197/xquery-40/xpath-40-autodiff.html#dt-static-context) must also be present in the [dynamically known function definitions](https://qt4cg.org/pr/197/xquery-40/xpath-40-autodiff.html#dt-dynamically-known-function-definitions) of the [dynamic context](https://qt4cg.org/pr/197/xquery-40/xpath-40-autodiff.html#dt-dynamic-context)", which follows from the statement in the definition of the *dynamically known function definitions* property that "It includes the [statically-known function definitions](https://qt4cg.org/pr/197/xquery-40/xpath-40-autodiff.html#dt-statically-known-function-definitions) as a subset, but may include other function definitions that are not known statically."  For economy of expression, one of these should probably be deleted; alternatively, one should be marked as a redundant reminder of the normative statement made elsewhere.  (I would make the definition be the normative statement and drop the bullet item or label it a consequence of the definition.)
* In 4.4.1 Function definitions, the sentence "The function is evaluated by executing its implementation, ..." makes my blood run cold.  I do not now have a proposal for alternative wording, but the sudden irruption of an imperative, procedural description into what is otherwise a declarative specification seems out of place.  Perhaps the change could just be to "The function is evaluated using a dynamic context that provides values for all the declared parameters, initialized as described in [4.4.1.2 Evaluating Static Function Calls](https://qt4cg.org/pr/197/xquery-40/xpath-40-autodiff.html#id-eval-static-function-call) below."
* In section 4.4.1.1 Static Function Call Syntax, missing text (bad hyperlink?) in the sentence "If the EQName in a static function call is an unprefixed [lexical QName](https://qt4cg.org/pr/197/xquery-40/xpath-40-autodiff.html#dt-qname), it is expanded using the [default function namespace](https://qt4cg.org/pr/197/xquery-40/xpath-40-autodiff.html#dt-default-function-namespace) in the ."  In the next paragraph, missing whitespace in "in the [static context](https://qt4cg.org/pr/197/xquery-40/xpath-40-autodiff.html#dt-static-context)using the rules".  (Other instances of missing whitespace immediately following a hyperlink are also visible, but I won't try to list them all.)
* Section 4.4.1.2 Evaluating Static Function Calls says, inter alia: "Any parameters that have not been associated with any argument expression by applying the above rules (which are necessarily optional parameters) are then associated with the default expression for the relevant parameter in the declared function."  
  It is not clear to me that the rules given earlier in the document guarantee that parameters not yet associated with any argument expression will be optional parameters.  (I found this sentence while looking for the place where the text would say that it is an error if at this point any required parameter does not yet have an argument expression.)
  In particular, consider a function definition named *my:foo* with two required and two optional parameters named *A*, *B*, *C*, and *D*.  I think the description of function definitions in section 2.2.1 Static Context tells us that its arity range is two to four, inclusive.  Consider then a static function call `my:foo(23, C := 42, D := "skiddoo")`, with one position and two keyword parameters.  I think item 1 in section 4.4.1.2 tells us the required arity is three.  That falls into the range two to four inclusive, so the call to `my:foo` is bound to the function definition for *my:foo*.  I think item 2 in the same section then tells us that *A* is bound to the expression `23`, *C* to `42`, and *D* to `"skiddoo"`.  
  Item 2 then tells me that any parameter that doesn't have an expression (here *B*) is "necessarily" an optional parameter.  But *B* is not an optional parameter.  It is false to say that it is, and it is doubly false to say that it is *necessarily* an optional parameter.  
  Perhaps I need to say that I take "necessarily" in this sentence to mean that the claim follows as a logical consequence of the rules already given.  If "necessarily" is meant here to mean that the state of affairs described is a pre-condition of error-free evaluation, then I think we would do better to find another way of making the point.
* In item 3 of the same list, some unmarked legacy text says "it is not required that an argument be evaluated if the function can evaluate its body without evaluating that argument."  I think this would be clearer if rephrased as "it is not required that an argument be evaluated if the function body can be evaluated without evaluating that argument."  Or "it is not required that an argument be evaluated if the function body can be evaluated it."

2022-10-25 04:46 UTC, Arithmeticus approved these changes
The revision is much clearer, and the simpler approach is to be preferred. Comments address only stylistic issues.

2022-10-25 04:46 UTC, Arithmeticus commented on specifications/xquery-40/src/expressions.xml
> +                  <p><termdef id="dt-arity-range" term="arity range">A <termref def="dt-function-definition"/> has an <term>arity range</term>
</term> -> </term>, (in this context "which" is non-restrictive)

2022-10-25 04:46 UTC, Arithmeticus commented on specifications/xquery-40/src/expressions.xml
> +                  <p>Implementations must ensure that no two declared functions have the same <termref
functions -> function definitions

2022-10-25 04:46 UTC, Arithmeticus commented on specifications/xquery-40/src/expressions.xml
> +               that are only known dynamically (appearing in the <termref def="dt-dynamically-known-function-definitions"/>).</p>
only known -> known only

2022-10-25 04:46 UTC, Arithmeticus commented on specifications/xquery-40/src/expressions.xml
> +                           <term>Statically-known function definitions.</term> This is a set of
Statically-known -> Statically known
The non-hyphenated form predominates 5:1, and is (in my editorial circles) to be preferred in constructions of [-ly adverb] [adj.] [noun].

2022-10-25 14:12 UTC, michaelhkay commented
Thanks for the comments.



On 25 Oct 2022, at 02:55, C. M. Sperberg-McQueen ***@***.******@***.***>> wrote:



Some incomplete and unsystematic notes:

  *   Is it intended that in section 2.2.1 Static Context of XPath, in the description of function definition, both required type and default value are glossed as "(a sequence type)"? It seems unexpected enough that I suspect a copy/paste error.

No, that's a typo.Thanks.

  *   I think the sentence "It is not acceptable to have a function definition with one required parameter and another (with the same name) having three optional parameters", would do its work better without the parenthesis marks.

I'll try to find a more elegant way of phrasing it.

  *   A propos the sentence "Implementations must ensure that no two declared functions have the same expanded QName<https://qt4cg.org/pr/197/xquery-40/xpath-40-autodiff.html#dt-expanded-qname> and overlapping arity ranges (even if the signatures are consistent)."
     *   The term "declared function" seems important and is used in several places, but is nowhere defined in the XPath spec. Does it mean a function definition in the statically known function definitions? ... in the dynamically known function definitions?

This should have been replaced by "function definitions" in the latest draft. The occurrences that remain somehow escaped a search of the XML content but are revealed by searching the HTML.

  *
     *   The requirement that no two declared functions have certain properties entails that we need a clean story about how to tell whether a declared function f1 is the same declared function as a declared function f2, or they are different functions. (I suspect this need is particularly acute when there is some possibility that the same module definition [for some definition of "same"] might by accident or design be referenced twice under different URIs, but the need is probably more general. I don't think we want complicated rules, just a clear one.)

The rules here go back to how XQuery and XSLT populate the static context, and are different between XQuery and XSLT.

In XQuery the rules are in 5.18: a function declaration in the query prolog, or a public function declaration in an imported module, cause a function definition to be added to the static context. I wish the rules on "import module" were clearer about module identity, but I don't think this is the place to fix them.

In XSLT the rules are more complex because of import precedence and packages, but I think the proposal spells them out in sufficient detail.

  *
  *   In section 2.3.4 Consistency constraints, the last bullet item appears to be redundant.

I suspect it's not the only thing that's said twice. I'll try to improve it.

  *   In 4.4.1 Function definitions, the sentence "The function is evaluated by executing its implementation, ..." makes my blood run cold.

Me too. I've always hated this. It's straight out of the 3.1 spec. I'll see if I can find something better.

  *   In section 4.4.1.1 Static Function Call Syntax, missing text (bad hyperlink?) in the sentence "If the EQName in a static function call is an unprefixed lexical QName<https://qt4cg.org/pr/197/xquery-40/xpath-40-autodiff.html#dt-qname>, it is expanded using the default function namespace<https://qt4cg.org/pr/197/xquery-40/xpath-40-autodiff.html#dt-default-function-namespace> in the ." In the next paragraph, missing whitespace in "in the static context<https://qt4cg.org/pr/197/xquery-40/xpath-40-autodiff.html#dt-static-context>using the rules". (Other instances of missing whitespace immediately following a hyperlink are also visible, but I won't try to list them all.)

Noted. Some of the whitespace problems seem to be associated with a switch from roman to italic text, and may be a rendition issue.

  *   Section 4.4.1.2 Evaluating Static Function Calls says, inter alia: "Any parameters that have not been associated with any argument expression by applying the above rules (which are necessarily optional parameters) are then associated with the default expression for the relevant parameter in the declared function."
It is not clear to me that the rules given earlier in the document guarantee that parameters not yet associated with any argument expression will be optional parameters.

Yes, I had problems convincing myself of this too. I thought I had proved it to myself, but your counter-example seems to show I was wrong.

  *   In item 3 of the same list, some unmarked legacy text says "it is not required that an argument be evaluated if the function can evaluate its body without evaluating that argument." I think this would be clearer if rephrased as "it is not required that an argument be evaluated if the function body can be evaluated without evaluating that argument."

Yes, that's definitely better.

  *   —

Reply to this email directly, view it on GitHub<https://github.com/qt4cg/qtspecs/pull/197#issuecomment-1289872495>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AASIQITEGZC7LQ6OT2HFFT3WE442HANCNFSM6AAAAAARBELBSE>.
You are receiving this because you commented.Message ID: ***@***.***>

2022-10-25 14:26 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                           <term>Statically-known function definitions.</term> This is a set of
Yes, again I've gradually learned that hyphenating adverb-adjective phrases seems to be much more the norm in BrE than in AmE. (The Oxford Manual of Style says use no hyphen if the adverb ends in "-ly", but use one otherwise (so "a well-known and happily married couple". Bizarre.)

2022-10-25 14:30 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                  <p>Implementations must ensure that no two declared functions have the same <termref
yes.

2022-10-25 14:30 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                  <p><termdef id="dt-arity-range" term="arity range">A <termref def="dt-function-definition"/> has an <term>arity range</term>
Yes, in my years of doing this job I've learned that Americans are much fussier about which/that distinctions than Brits.

2022-10-25 14:43 UTC, Arithmeticus commented on specifications/xquery-40/src/expressions.xml
> +                  <p><termdef id="dt-arity-range" term="arity range">A <termref def="dt-function-definition"/> has an <term>arity range</term>
Here it's just the comma, not the which/that distinction, which the Cambridge Grammar of English Language has convinced me of as being unsound, _pace_ Garner.

2022-11-01 15:12 UTC, rhdunn reviewed
Overall, this looks good. I've left some comments, and have comments from my previous review.

2022-11-01 15:20 UTC, rhdunn commented on specifications/xslt-40/src/xslt.xml
> +                  the static context does not include variables bound in preceding-sibling <elcode>xsl:param</elcode> elements.</p>
Q: Should we also call this out in the XPath and XQuery specs? -- Parameters declared before the current parameter's default expression are not included in the static context of that expression.

2022-11-07 19:36 UTC, rhdunn commented on specifications/xquery-40/src/expressions.xml
> +                        with the default expression for the relevant parameter in the declared function.</p></item>
This is now resolved.

2022-11-15 17:29 UTC, ndw commented
Approved at [meeting 011, 15 November 2022](https://qt4cg.org/meeting/minutes/2022/11-15.html)

2022-11-15 17:29 UTC, merged