NW for MK: subtyping (196)
qt4cg/qtspecs pull request #202
Opened 2022-10-10 09:11 UTC by ndw

MK: improve pres of XPath §3.7 (subtyping) and clarify notion of dynamic type

This PR is intended to be technically equivalent to #196.

I've reworked a series of MK commits so that they are independent; I fear we would wind up with merge conflicts otherwise and cleaning up the merge conflicts, without accidentally making some other change, seemed riskier than just teasing them apart and making them independent before we accept and merge them.

2022-10-19 16:34 UTC, ndw commented
Formatted versions of the specifications with this PR applied [are available](https://qt4cg.org/#pr-202)

2022-10-25 06:41 UTC, rhdunn requested changes
Overall, I think this is a huge improvement:
1. Grouping the rules makes them easier to follow.
2. Splitting out multi-clause rules into numbered points (one for each assertion clause) also makes them easier to follow.
3. The examples in each section are great -- they help to understand some of the rules, and it is then clearer what the rules are matching.

2022-10-25 06:41 UTC, rhdunn commented on specifications/xquery-40/src/expressions.xml
> +                  Every value matches one or more <termref def="dt-sequence-type">sequence types</termref>.
Editorial: "sequence types" -> "sequence type".

2022-10-25 14:16 UTC, cmsmcq commented
In section 3 Types, XQuery says 

> With the exception of the generic types item(), which matches all items, and xs:error, which matches no items, item types match either [atomic values](https://qt4cg.org/pr/202/xquery-40/xquery-40-autodiff.html#dt-atomic-value), [nodes](https://qt4cg.org/pr/202/xquery-40/xquery-40-autodiff.html#dt-node), or [functions](https://www.w3.org/TR/xpath-datamodel-31/#dt-function-item)DM31.

I do not understand the last sentence.  The contrast with `item()` suggests that the property being pointed out is that every other sequence type includes as values a subset of all atomic values or a subset of all nodes or a subset of all function items.  But in that case there is no contrast with `xs:error`.

2022-10-25 14:45 UTC, michaelhkay commented
It's trying to draw a contrast: there are some cases where values carry some kind of intrinsic type as part of their state (or value space), there are other cases where matching a value against a type is purely algorithmic.

Atomic values are in the first category. 3 as an instance of xs:long is not the same thing as 3 as an instance of xs:positiveInteger - if you pass these two values to a function that expects an xs:integer, the code in the function can distinguish them. The type is part of what you pass across. These values truly have something that could be called a "dynamic type". They are Platonic types, acquired at the point where the value comes into being, for example xs:long(3) constructs a value labelled as an xs:long.

Sequences, maps, and arrays are different. (1,2,3) as an instance of xs:integer* is not different from (1,2,3) as an instance of xs:integer+. If these two values are passed to a function that expects item()*, the code in the function can't distinguish them. Sequences can be tested for conformance against a type, but they don't carry a type with them as a separate label. These are Aristotelian types (duck types), determined by applying a predicate.

Unfortunately it's not quite correct to say that for atomic values, there is a narrowest type. xs:ID and xs:NCName have the same value space, neither is narrower than the other in that sense. A value is an xs:ID not because it satisfies all the rules for the value space, but because it was born with that type.


On 25 Oct 2022, at 15:10, C. M. Sperberg-McQueen ***@***.******@***.***>> wrote:



In XQuery section 2.2.3.2 Dynamic Evaluation Phase, I am a little puzzled by the note

For atomic values in particular, there is always one dynamic type<https://qt4cg.org/pr/202/xquery-40/xquery-40-autodiff.html#dt-dynamic-type> that is specifically associated with the value, so we can refer to the dynamic type of an atomic value without ambiguity; this will be a subtype<https://qt4cg.org/pr/202/xquery-40/xquery-40-autodiff.html#dt-subtype> of all the other types that it matches.

I'm not sure what specifically associated with means, but on first reading I assumed that of course it would mean the declared type, or the type to which the old type conversion rules would map the expression. So declare variable $my:x as xs:integer := 42 would associate the value of my:x with the type xs:integer. But xs:integer is not a subtype of the other built-in types of which 42 is an instance.

On further reflection, the note appears to mean that for every value v a processor now has the obligation to identify the narrowest built-in type to which is conforms and specifically associating the value with that type. That feels like a big change.

(I specify built-in types because there is and can be no guarantee that when user-specified types are taken into account there will always be a narrowest type for a value.)

I hope that all it is really necessary to say is that for any atomic value, there is a narrowest built-in type which can be identified.

—
Reply to this email directly, view it on GitHub<https://github.com/qt4cg/qtspecs/pull/202#issuecomment-1290623128>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AASIQIVIAA4NKLL55OA6MKTWE7S7DANCNFSM6AAAAAARBEX5LQ>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2022-10-25 18:17 UTC, cmsmcq commented
With regard to the note about dynamic types of atomic values, MK and I seem to be talking at cross purposes; I don't know what the source of our mutual misunderstanding is, so I don't know a good way to clear it up.  Perhaps one way is to start again.  In both XPath and XQuery we find a note reading

> **Note:**

> For atomic values in particular, there is always one [dynamic type](https://qt4cg.org/pr/202/xquery-40/xpath-40-autodiff.html#dt-dynamic-type) that is specifically associated with the value, so we can refer to the dynamic type of an atomic value without ambiguity; this will be a [subtype](https://qt4cg.org/pr/202/xquery-40/xpath-40-autodiff.html#dt-subtype) of all the other types that it matches.

In [his comment](https://github.com/qt4cg/qtspecs/pull/202#issuecomment-1290672382), MK notes that atomic values effectively carry a type label around with them.  So far, so good.  I believe that in some cases this will be the static type, and in other cases not.  I think that this is what some people refer to as manifest typing, and some refer to as boxed values.

Some things trouble me about the note:
* It says "this [sc. the dynamic type specifically associated with a value] will be a subtype of all the other types it [sc. the value] matches."  
  To take MK's example:  3 as an instance of xs:long is distinct from 3 as an instance of xs:integer.  So far, so good.  I think MK is saying that in the one case, the value 3 is "specifically associated" (as the note says) with xs:long, and in the other case it is specifically associated with xs:integer.  OK, that makes sense to me (although if I didn't already understand that, I don't think the note would have conveyed that information to me).  
  It is possible to think of 3 specifically associated with xs:long because 3 is an instance of xs:long, or equivalently becase 3 matches the type xs:long. (I think this is common ground, and maybe should go without saying.)  And ditto for 3 and xs:integer.  I believe that what that means is that "the" dynamic type specifically associated with the value 3 will sometimes be xs:long and xs:integer. Using XSD terms, I would say that 3 is in the value space both of xs:long and xs:integer.
  The sentence quoted above says that when the dynamic type of 3 is xs:long, then xs:long "will be a subtype of all the other types" matched by 3.  So xs:long will be a subtype of xs:integer.  
  The same sentence says that when the dynamic type of 3 is xs:integer, then xs:integer will be a subtype of all the other types matched by 3.  So xs:integer is a subtype of xs:long.  
  But the only way I can see for xs:long and xs:integer each to be a subtype of each other is for them to be the same type.  They aren't.
  I infer that the sentence quoted is in error.
* The note as a whole seems to reflect an assumption that for any atomic value *v*, there will be a single type *T* which is a subtype of every other atomic type containing *v*.  But this will not be the case in general.  It will not even (contrary to what I believed a few hours ago) be true for all XSD built-in types.
  For example:  3 is an instance of xs:long and of xs:unsignedLong.  Neither is derived from the other, and if I am reading the definition of subtype correctly, neither is a subtype of the other as that term is used in XPath and XQuery.

2022-10-25 18:32 UTC, cmsmcq commented
In XPath, section 3.7 Subtype Relationships, a paragraph containing the sentence

> When the judgement subtype(A, B) is true, it is always the case that for any value V, (V instance of A) implies (V instance of B).

is replaced by text containing the converse statement:

> A type A is a subtype of B if it can be established that every value matched by A is also matched by B.] 

I think "if it can be established" should probably be reworded as "if it can be established using the rules in this section", because it's possible (and sometimes not very hard) to establish subset relations among value spaces that cannot be established by the rules given, or by any set of rules we would like to impose on implementations.

But the conditional is also now pointing in the wrong direction.  It used to say, correctly (I think, possibly modulo some disastrous bugs in XSD) that if the rules license the judgement subtype(A, B), then the value space of A is a subset of the value space of B.  (That is, in logical terms, it claimed that the inference rules were sound.)  Now it claims the converse:  that if the subset relation holds on the value spaces, the judgement (in its new form) holds on the types.  So it now claims that the inference rules are complete.

The parts of the inference rules I have looked at, while thinking about the value 3 and the various types of which it is an instance, do not justify the claim that the rules are complete.  I do not think we can make the rules complete for all schema-defined atomic types, so I do not think we should spend time trying.

2022-10-25 19:41 UTC, michaelhkay commented
>

  *   The same sentence says that when the dynamic type of 3 is xs:integer, then xs:integer will be a subtype of all the other types matched by 3. So xs:integer is a subtype of xs:long.

You can't talk about whether a type is matched by (or matches) 3. You can only talk about whether it is matched by xs:long(3) or xs:int(3) or xs:positiveInteger(3). These are different (distinguishable) atomic values; an atomic value consists of a raw value and a type label. For atomic values, "V instance of T" is true iff the type label (or "dynamic type") of V is a subtype of T. The type label is the type that the value was born with: xs:long(3) has the type label xs:long.

I don't like it and I fought against it, but that's the way it is. In XPath the bare literal 3 means xs:integer(3), and if you test "3 instance of xs:positiveInteger", it is interpreted as "xs:integer(3) instance of xs: positiveInteger", and the answer is false.


  *   an assumption that for any atomic value v, there will be a single type T which is a subtype of every other atomic type containing v

I'm not quite sure what you mean here by "containing". But if you mean the instance-of releationship, then this assumption is true. If an atomic value V carries the type label T, then T will be a subtype of every type U for which (V instance of U) holds.

The same is true, incidentally, of schema-validated element and attribute nodes. If an attribute node code="1234" is validated against the simple type xs:integer, then `A instance of attribute(*, xs:integer)` will be true, and `A instance of attribute(*, xs:positiveInteger)` will be false.

2022-10-25 19:43 UTC, michaelhkay commented
I found it difficult to revise the subtyping rules without first clarifying the basics. And it would be harder to pull apart the edits into separate commits now.

On 25 Oct 2022, at 19:48, Reece H. Dunn ***@***.******@***.***>> wrote:



I wonder if it makes sense to separate out the changes w.r.t. the wording changes around dynamic types and the changes to refer to values vs types from the changes to the subtype rules themselves.

I find that the subtype rule changes themselves (outside of the changes w.r.t. types vs values) make that section a lot easier to read and understand.

—
Reply to this email directly, view it on GitHub<https://github.com/qt4cg/qtspecs/pull/202#issuecomment-1290997357>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AASIQIQTVGASZBROEUKWUBTWFATRTANCNFSM6AAAAAARBEX5LQ>.
You are receiving this because you commented.Message ID: ***@***.***>

2022-10-25 21:56 UTC, cmsmcq commented
In [his comment](https://github.com/qt4cg/qtspecs/pull/202#issuecomment-1291049535), MK says

> You can't talk about whether a type is matched by (or matches) 3. You can only talk about whether it is matched by xs:long(3) or xs:int(3) or xs:positiveInteger(3). 

I am sorry, but I am again (or still?) lost.  If we cannot talk about whether a type is matched by, or matches, a value, then the note I was commenting on, and the definition of *dynamic type*, and the accompanying discussion need to be changed, because they use that form of words repeatedly (emphasis added):

* "Every value **matches one or more sequence types**."
* "A value is said to have a dynamic type T if **it matches ... the sequence type T**."
* "... one of the dynamic types **that a value matches** ..."
* "... all the other types **that it matches** ..."

I don't have any deep attachment to the form of words in question.  But it does seem to be the form of words used in the proposal we are considering.  If that form of words is unacceptable, what is it doing in the proposal?

Also, I do not know what it means to say that a type *T* "is matched by xs:long(3)".  Or, if the antecedent of "it" is the number 3, what it means to say that 3 "is matched by xs:long(3)".

2022-10-25 22:10 UTC, michaelhkay commented
On 25 Oct 2022, at 22:56, C. M. Sperberg-McQueen ***@***.******@***.***>> wrote:



In his comment<https://github.com/qt4cg/qtspecs/pull/202#issuecomment-1291049535>, MK says

You can't talk about whether a type is matched by (or matches) 3. You can only talk about whether it is matched by xs:long(3) or xs:int(3) or xs:positiveInteger(3).

I am sorry, but I am again (or still?) lost. If we cannot talk about whether a type is matched by, or matches, a value,

The point is that 3 is not a value, except to the extent that as an XPath literal it represents the value xs:integer(3).

Of course the terminology is dreadful here. An atomic value is a tuple comprising a type T and a value V. Matching of an atomic value to a type always considers the (T, V) tuple, not just the V part.

(We call V a value, but it isn't a value in the XDM sense. Only the tuple (T, V) is a value. We should probably refer to V as a "point in the value space", or a "datum", or an "atom").

2022-10-25 22:18 UTC, cmsmcq commented
MK writes: 
> The point is that 3 is not a value, except to the extent that as an XPath literal it represents the value xs:integer(3). Of course the terminology is dreadful here. An atomic value is a tuple comprising a type T and a value V. Matching of an atomic value to a type always considers the (T, V) tuple, not just the V part. (We call V a value, but it isn't a value in the XDM sense. Only the tuple (T, V) is a value. We should probably refer to V as a "point in the value space", or a "datum", or an "atom").

Oh, my.  Well, thank you, I guess.  This does help me understand parts of the discussion we have been having, or trying to have.  It would be nice to help readers avoid the feeling of mental whiplash I am currently experiencing;  I will see whether I can think of any useful suggestions.

2022-11-11 23:30 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +               <p diff="chg" at="B">A value may conform with a dynamic type that is more specific than the <termref def="dt-static-type"/>
Using "match". A value matches a type.

2022-11-11 23:33 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +               of another are given in <specref ref="id-seqtype-subtype"/>. They rule for deciding whether
OK

2022-11-11 23:37 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +               produces a string) but they have the same value space.
Now sorted.

2022-11-11 23:41 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                  and <code>B</code>, as determined in <specref ref="id-itemtype-subtype"/>.</p>
Done.

2022-11-11 23:47 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                           <p><var>A</var> is <code>xs:error</code>.</p>
I wasn't consciously changing it, but I believe it is correct. xs:error matches nothing, which makes it a subtype of any type that matches something: it's the bottom of the type lattice (to the extent that we have a lattice).

2022-11-11 23:55 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                     then <var>M</var> <term>wildcard-matches</term> <var>N</var> is true if any of the following apply:</termdef></p>
Multi-paragraph definitions are difficult to mark up (I believe one of the specs uses them, but it's clumsy and doesn't look good in the glossary). So yes, the second approach is preferable.

2022-11-12 00:00 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                                 or <code>element(<var>A/n</var>, <var>T</var>?)</code> for some type <var>T</var></p></item>
Yes. "for any" and "for some" aren't interchangeable, but "for any" is better here.

2022-11-12 00:03 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                              <p>Function return types are covariant because this rule invokes <code><var>R/A</var> ⊑ <var>R/B</var></code> for return types.
Changed to "requires"

2022-11-12 00:09 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                              <p>Function return types are covariant because this rule invokes <code><var>R/A</var> ⊑ <var>R/B</var></code> for return types.
And while on the subject, I've changed all occurrences of "invoking a function" to "calling a function".

2022-11-12 00:11 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                  Every value matches one or more <termref def="dt-sequence-type">sequence types</termref>.
Eh? "One or more sequence types", surely?

2022-11-12 10:12 UTC, rhdunn commented on specifications/xquery-40/src/expressions.xml
> +                  Every value matches one or more <termref def="dt-sequence-type">sequence types</termref>.
Looking at https://english.stackexchange.com/questions/13284/which-is-correct-one-or-more-is-or-one-or-more-are both the singular or plural are valid. I'm thinking of it as "one (or more than one) sequence type" as noted in one of the comments, hence my suggestion to use the singular.

The reply referencing the copyeditor's handbook notes that it states:
> 18. One or more x. The expression one or more always takes a plural verb.

As such, I'm happy for this to remain plural.

2022-11-12 10:13 UTC, rhdunn commented on specifications/xquery-40/src/expressions.xml
> +                           <p><var>A</var> is <code>xs:error</code>.</p>
That makes sense. I wonder if there should be a note pointing that out.

2022-11-13 21:32 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                           <p><var>A</var> is <code>xs:error</code>.</p>
Actually, it's not a new rule. 3.1 stated "Ai is a pure union type, and every type t in the transitive membership of Ai satisfies subtype-itemType(t, Bi)." I believe that xs:error is a pure union type; its transitive membership is empty; therefore every type in its transitive membership satisfies P, where P is any predicate you care to mention. I'll add a note that the rule is technically redundant.

2022-11-13 21:43 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                              <p>For example:</p>
I've changed the tagging so these are now `<example>` elements; I've also changed the stylesheet so that `example` elements in the XPath/XQuery spec are rendered the same as in the F&O spec. This may need some review.

2022-11-13 21:47 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                  <head>Node Types: General Rules</head>
I'm reasonably content to leave the section hierarchy as it is.

2022-11-13 21:51 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                  <head>Functions</head>
I'm very reluctant to go to fifth-level headings.

2022-11-13 22:00 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                  <head>Node Types: Element Tests</head>
OK. I'd prefer to dodge the question of whether `element(*)` and `element()` are different types, or different ways of expressing the same type...

2022-11-13 22:00 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                  <head>Node Types: Element Tests</head>
OK. I'd prefer to dodge the question of whether `element(*)` and `element()` are different types, or different ways of expressing the same type...

2022-11-13 22:14 UTC, michaelhkay commented on specifications/xquery-40/src/expressions.xml
> +                  <head>Node Types: Element Tests</head>
Actually, I didn't entirely dodge that question, in the intro to §3.7.2 I cover myself by suggesting "equivalent forms such as element() and element(*) are normalized."

2022-11-16 10:02 UTC, merged