Adjusted serialization step 5 note
qt4cg/qtspecs pull request #626
Opened 2023-07-20 01:47 UTC by Arithmeticus

This brief edit addresses issue #556, which I've chosen to handle apophatically.

2023-07-20 07:22 UTC, ndw approved these changes

2023-07-20 20:57 UTC, michaelhkay requested changes
I don't feel the phrase "at the result of serialization is a Unicode character sequence that is not a stream of octets" adds any clarity. I think the real point is that the result of serialization may be sent to a destination that requires Unicode characters to be represented in a particular way (for example, a Java StringBuffer), and when that is the case, the serializer will represent the characters in whatever way is required, which involves skipping the encoding phase,

2023-07-20 21:09 UTC, ChristianGruen commented
If we want to get rid of “stream”, maybe we can simply say “sequence of Unicode characters”.

2023-07-21 00:48 UTC, Arithmeticus commented
Thanks for the comments. See new commit.

2023-07-22 13:41 UTC, merged