695: Added xref to fn:slice()
qt4cg/qtspecs pull request #786
Opened 2023-10-26 22:21 UTC by Arithmeticus

This closes #695 .

2023-10-26 22:48 UTC, michaelhkay requested changes
Did you test this? I think a `<note>` element can't contain text directly, it needs to be wrapped in a `<p>`.

2023-10-27 00:31 UTC, Arithmeticus commented
Fixed in latest commit. I tried to point to id `func-slice`, but the build resulted in a markup error:
![image](https://github.com/qt4cg/qtspecs/assets/2113262/3ae4ead9-9887-4ed9-a9f7-3d2183c50798)

I don't think this is expected behavior, perhaps precipitated by the diff attribute in the <div3> with id `func-slice`? For the time being the pointer is now to the parent <div2>.

2023-10-30 13:25 UTC, ChristianGruen approved these changes

2023-10-31 17:10 UTC, ndw commented
The CG agreed to merge this PR at [meeting 052](https://qt4cg.org/meeting/minutes/2023/10-31.html)

2023-10-31 17:10 UTC, merged