Minor edits, XQFO chh. 7, 8
qt4cg/qtspecs pull request #804
Opened 2023-10-31 21:32 UTC by Arithmeticus

In addition to a minor typo, note the following:
- rearrangement of a rule for `$input` (the original syntax, mixing types and derived types, confused me)
- examples in `X-from-Y` duration functions to help illustrate the problem when mixing the two components of a duration.

2023-10-31 21:35 UTC, ChristianGruen approved these changes

2023-11-02 00:28 UTC, michaelhkay requested changes
There's a typo ("months"), and bad indentation, in the new example for months-from-duration(). The indentation problem is also seen in other new XX-from-duration examples that have been added.

2023-11-02 02:23 UTC, Arithmeticus commented
Thanks, should be fixed now.

2023-11-07 17:20 UTC, ndw commented
The group agreed to merge this PR at [meeting 053](https://qt4cg.org/meeting/minutes/2023/11-07.html)

2023-11-07 17:58 UTC, merged