779 hash function
qt4cg/qtspecs pull request #937
Opened 2024-01-10 04:03 UTC by Arithmeticus

First draft of hash function, proposed in #779.

Error message left as to-do item; guidance from editors appreciated.

I opted to leave out wrapper/cryptographic functionality, such as salting, and to demonstrate via example how it could be done by a developer on their own. In my opinion what we need here is a simple atomic function that can be incorporated into other molecular functions.

I may tinker with the prose description up to CG discussion, so comments are welcome.

2024-01-10 13:01 UTC, ChristianGruen requested changes
Thanks, looks good otherwise.

2024-01-10 13:01 UTC, ChristianGruen commented on specifications/xpath-functions-40/src/function-catalog.xml
> +         <fos:version version="4.0">Newly proposed for 4.0.</fos:version>
```suggestion
         <fos:version version="4.0">New in 4.0.</fos:version>
```

…on the other hand, the document is not very consistent in this matter.

2024-01-15 17:25 UTC, Arithmeticus commented on specifications/xpath-functions-40/src/function-catalog.xml
> +            through the specified hash or checksum function. Output is always lowercase.</p>
For lowercase, I was taking my lead from common usage/expectations as well as the specs for the MD5 and SHA-1 algorithms, which prefer lowercase.

2024-01-15 17:35 UTC, Arithmeticus commented
Thanks, Christian, for the excellent suggestions and catches. Latest commit addresses them all, + a few more. To-do / desiderata would be examples using binary input.

2024-01-15 17:36 UTC, Arithmeticus commented on specifications/xpath-functions-40/src/function-catalog.xml
> +            <code>fn:lower-case(fn:replace($function, '\W+', ''))</code>. </p>
I was looking for a way to forgive a user if they couldn't remember if a name had a hyphen or not, but my solution was too lenient.

2024-01-15 18:38 UTC, ChristianGruen requested changes
…some more observations, all minor.

2024-01-15 18:38 UTC, ChristianGruen commented on specifications/xpath-functions-40/src/function-catalog.xml
> +               default="fn:string(.)"/>
The default for the first argument should be dropped.

2024-01-15 18:38 UTC, ChristianGruen commented on specifications/xpath-functions-40/src/function-catalog.xml
> +               <code>xs:base64Binary</code> or <code>xs:hexBinary</code> it is cast to a sequence of
Maybe “converted” or “translated”? “cast” may imply that “sequence of octets” is a data type.

2024-01-15 18:38 UTC, ChristianGruen commented on specifications/xpath-functions-40/src/function-catalog.xml
> +         <p>If <code>$value</code> is an instance of <code>xs:string</code> it is cast to a sequence
```suggestion
         <p>If <code>$value</code> is an instance of <code>xs:string</code>, it is cast to a sequence
```

2024-01-16 07:40 UTC, ChristianGruen commented on specifications/xpath-functions-40/src/function-catalog.xml
> +            <fos:arg name="value" type="union(xs:string, xs:hexBinary, xs:base64Binary)"/>
```suggestion
            <fos:arg name="value" type="union(xs:string, xs:hexBinary, xs:base64Binary)?"/>
```

2024-01-23 12:34 UTC, benibela commented
I still do not understand why this would be put into fn and not into a separate hash module. Or it could fit into Expath's binary module

md5 and sha-1 are already deprecated anyways

2024-01-23 17:43 UTC, ndw commented
The CG agreed to merge this PR at [meeting 062](https://qt4cg.org/meeting/minutes/2024/01-23.html)

2024-01-23 17:50 UTC, merged