937 revised in light of CG feedback
qt4cg/qtspecs pull request #995
Opened 2024-02-03 03:34 UTC by Arithmeticus

This revises #937 (catalyzed by #779) in light CG discussion that approved the PR.

* Output is now `xs:hexBinary?`
* Second parameter `$algorithm` replaced with an option map. In the specs I avoided `fos:values/fos:value`, because this would disallow for case/space normalization, and it would effectively disallow any implement-defined algorithms not on the list of three algorithms, and trigger the dynamic error described in rule 6 in the [option parameter conventions](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#option-parameter-conventions).
* Options map has only one option. It doesn't make sense to provide an option changing the kind of output.
* I think this is the first example of an options map where the `fos:meaning` has rich text (paragraphs, unordered lists). It builds and renders fine locally.
* Extra note on the output format.
* Examples are expressed as chained functions, to illustrate how to get the customary string values.

2024-02-03 14:35 UTC, ChristianGruen commented
Thanks for the revision. I didn't have time for a full review yet, but I wonder if lower-case is consistently the more “customary” one. Can we find a reliable reference for this?

Personally, I’ve observed both variants in the past, and the representation usually depended on how binaries were converted to strings by the responsible language or tool.

2024-02-03 14:40 UTC, ChristianGruen commented on specifications/xpath-functions-40/src/function-catalog.xml
> +         <p>A dynamic error is raised ([TODO: error code]) if the effective value of the option
(next line: `<code>$algorithm</code>` → `<code>algorithm</code>`.

2024-02-03 19:36 UTC, ChristianGruen requested changes

2024-02-03 19:36 UTC, ChristianGruen commented on specifications/xpath-functions-40/src/function-catalog.xml
>                 <code>$algorithm</code> is not one of the values supported by the implementation.</p>
```suggestion
               <code>algorithm</code> is not one of the values supported by the implementation.</p>
```

2024-02-03 19:36 UTC, ChristianGruen commented on specifications/xpath-functions-40/src/function-catalog.xml
>              </fos:test>
The presentation of the examples…

<img src='https://github.com/qt4cg/qtspecs/assets/196589/b3bf463b-1ef6-4158-8d52-12438751c04c' width='500'/>

…could be revised by…

* using newlines for each arrow operator/operand, or
* using the “vertical layout”, i.e., by inserting `</fos:example><fos:example>` after each `</fos:test>`. See for example `fn:concat`:

<img src='https://github.com/qt4cg/qtspecs/assets/196589/b48fd9f4-269b-4bc2-b0d2-20e9202c7c7e' width='500'/>

2024-02-03 19:36 UTC, ChristianGruen commented on specifications/xpath-functions-40/src/function-catalog.xml
> +               <fos:expression>hash($doc) => string() => lower-case()</fos:expression>
One `lower-case()` conversion example may suffice.

2024-02-03 19:36 UTC, ChristianGruen commented on specifications/xpath-functions-40/src/function-catalog.xml
> +            uppercase, and the more customary lowercase requires further adjustment.</p>
See my previous comment: A reference reg. lowercase could be helpful.

2024-02-03 19:36 UTC, ChristianGruen commented on specifications/xpath-functions-40/src/function-catalog.xml
> +         <p>The entries that may appear in the <code>$options</code> map are as follows. The detailed rules
If I remember correctly, we’ve chosen to move the `algorithm` into a map, as a map may contain other entries that could be utilized by a proprietary algorithm. This should probably be mentioned; otherwise, one may wonder why a map needs to be specified if there’s just one option defined.

@ndw Do you have an example in mind for a custom hash algorithm with additional parameters?

2024-02-04 04:07 UTC, Arithmeticus commented on specifications/xpath-functions-40/src/function-catalog.xml
> +         <p>The entries that may appear in the <code>$options</code> map are as follows. The detailed rules
@ChristianGruen I had hoped that the cross-reference to option parameter conventions would suffice, and not require mentioning that the map can have implementation-defined entries (already stated at the OPCs).

2024-02-04 04:22 UTC, Arithmeticus commented on specifications/xpath-functions-40/src/function-catalog.xml
>              </fos:test>
I've tried the `fn:concat` example, but it doesn't rendered the same, I think because of the use of variables within the examples. Thanks for the tip that the space in `fos:expression` is preserved in the specs.

2024-02-04 04:24 UTC, Arithmeticus commented
Thanks for the pointers, mostly addressed in new commit.

2024-02-04 07:31 UTC, ChristianGruen approved these changes

2024-02-06 17:11 UTC, ndw commented
The CG agreed to merge this issue without discussion at [meeting 064](https://qt4cg.org/meeting/minutes/2024/02-06.html)

2024-02-06 17:25 UTC, merged